// <auto-generated />
using System;
using EntityFrameworkCore.Jet.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicStore.DB.DataAccess;

#nullable disable

namespace MusicStore.DB.Migrations
{
    [DbContext(typeof(MusicStoreDbContext))]
    [Migration("20231016125344_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnsembleMusicant", b =>
                {
                    b.Property<Guid>("MusicantEnsemblesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicantsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MusicantEnsemblesId", "MusicantsId");

                    b.HasIndex("MusicantsId");

                    b.ToTable("EnsembleMusicant");
                });

            modelBuilder.Entity("MusicStore.DB.Models.CompactDisk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountInStock")
                        .HasColumnType("integer");

                    b.Property<int>("CountSoldCurrentYear")
                        .HasColumnType("integer");

                    b.Property<int?>("CountSoldPreviousYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ManufacturingCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WhosalerPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingCompanyId");

                    b.HasIndex("MusicId");

                    b.ToTable("CompactDisks");
                });

            modelBuilder.Entity("MusicStore.DB.Models.Ensemble", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComposerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrchestraConductorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PerformanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.HasIndex("ComposerId");

                    b.HasIndex("LeaderId");

                    b.HasIndex("OrchestraConductorId");

                    b.ToTable("Ensembles");
                });

            modelBuilder.Entity("MusicStore.DB.Models.EnsembleMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Patronomyc")
                        .HasColumnType("longchar");

                    b.Property<string>("ProfileLink")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.ToTable("EnsembleMembers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("EnsembleMember");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MusicStore.DB.Models.ManufacturingCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("ShortName")
                        .HasColumnType("longchar");

                    b.Property<decimal>("WhosalerPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturings");
                });

            modelBuilder.Entity("MusicStore.DB.Models.Music", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.ToTable("Musics");
                });

            modelBuilder.Entity("MusicStore.DB.Models.MusicalMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Arrangement")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<double>("Duration")
                        .HasColumnType("double");

                    b.Property<string>("Dynamics")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Interpretation")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<Guid>("PerformanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tempo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId")
                        .IsUnique();

                    b.ToTable("MusicalMetadatas");
                });

            modelBuilder.Entity("MusicStore.DB.Models.Performance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.HasIndex("MusicId");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("MusicStore.DB.Models.Musicant", b =>
                {
                    b.HasBaseType("MusicStore.DB.Models.EnsembleMember");

                    b.Property<string>("MusicalInstrument")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasDiscriminator().HasValue("Musicant");
                });

            modelBuilder.Entity("EnsembleMusicant", b =>
                {
                    b.HasOne("MusicStore.DB.Models.Ensemble", null)
                        .WithMany()
                        .HasForeignKey("MusicantEnsemblesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStore.DB.Models.Musicant", null)
                        .WithMany()
                        .HasForeignKey("MusicantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicStore.DB.Models.CompactDisk", b =>
                {
                    b.HasOne("MusicStore.DB.Models.ManufacturingCompany", "ManufacturingCompany")
                        .WithMany("ManufacturedDisks")
                        .HasForeignKey("ManufacturingCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStore.DB.Models.Music", "Music")
                        .WithMany("CompactDisks")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufacturingCompany");

                    b.Navigation("Music");
                });

            modelBuilder.Entity("MusicStore.DB.Models.Ensemble", b =>
                {
                    b.HasOne("MusicStore.DB.Models.EnsembleMember", "Composer")
                        .WithMany("ComposerEnsembles")
                        .HasForeignKey("ComposerId");

                    b.HasOne("MusicStore.DB.Models.EnsembleMember", "Leader")
                        .WithMany("LeaderEnsembles")
                        .HasForeignKey("LeaderId");

                    b.HasOne("MusicStore.DB.Models.EnsembleMember", "OrchestraConductor")
                        .WithMany("OrchestraConductorEnsembles")
                        .HasForeignKey("OrchestraConductorId");

                    b.Navigation("Composer");

                    b.Navigation("Leader");

                    b.Navigation("OrchestraConductor");
                });

            modelBuilder.Entity("MusicStore.DB.Models.MusicalMetadata", b =>
                {
                    b.HasOne("MusicStore.DB.Models.Performance", "Performance")
                        .WithOne("MusicalMetadata")
                        .HasForeignKey("MusicStore.DB.Models.MusicalMetadata", "PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("MusicStore.DB.Models.Performance", b =>
                {
                    b.HasOne("MusicStore.DB.Models.Ensemble", "Ensamble")
                        .WithOne("Performance")
                        .HasForeignKey("MusicStore.DB.Models.Performance", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStore.DB.Models.Music", "Music")
                        .WithMany("Performances")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ensamble");

                    b.Navigation("Music");
                });

            modelBuilder.Entity("MusicStore.DB.Models.Ensemble", b =>
                {
                    b.Navigation("Performance")
                        .IsRequired();
                });

            modelBuilder.Entity("MusicStore.DB.Models.EnsembleMember", b =>
                {
                    b.Navigation("ComposerEnsembles");

                    b.Navigation("LeaderEnsembles");

                    b.Navigation("OrchestraConductorEnsembles");
                });

            modelBuilder.Entity("MusicStore.DB.Models.ManufacturingCompany", b =>
                {
                    b.Navigation("ManufacturedDisks");
                });

            modelBuilder.Entity("MusicStore.DB.Models.Music", b =>
                {
                    b.Navigation("CompactDisks");

                    b.Navigation("Performances");
                });

            modelBuilder.Entity("MusicStore.DB.Models.Performance", b =>
                {
                    b.Navigation("MusicalMetadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
